name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: dev-website
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GCR_SECRET: ${{ secrets.GCR_SECRET }}
  DEPLOYMENT_NAME: dev-website

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ env.GCR_SECRET }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: gcloud --quiet auth configure-docker

    - name: Build and push Docker Image
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
