apiVersion: v1
kind: Service
metadata:
  name: dev-website-service
  namespace: website
spec:
  type: NodePort
  selector:
    app: dev-website
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
      nodePort: 30000