apiVersion: v1
kind: Service
metadata:
  name: dev-website-service
  labels:
    app: dev-website
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    app: dev-website
